### ISSUE TITLE
user, auth 모듈의 dto 이름 수정

### ISSUE THREAD

**Issue by kyeonkim** [sasaping/sasaping-system#62]
## 어떤 기능인가요?

- 전체 빌드 시 user, auth의 dto 모듈 이름이 같아버리니 어떤 서비스의 dto인지 찾지 못하는 에러가 발생
- user, auth dto의 이름을 auth_dto 와 같이 수정해야함

## 작업 상세 내용(선택)

- [x] user
- [x] auth

**Comment by eggnee** [comment]
감사합니다!!
